environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#

build_script:
  - gradlew build --info
  - gradlew fatJar --info
  - gradlew pureJar --info
#

artifacts:
  - path: 'build\libs\engine-all-1.5.2.jar'
    name: frice
#
